version: '2'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
               
    consumer:
        build:
            context: .
            dockerfile: ubuntu.14.04-x64/Consumer/linux-consumer.docker
            
        environment:
            Tachyon_RedisConnectionMultiplexer: 192.168.51.11 
        
        entrypoint:
            - dotnet
            - ubuntu.14.04-x64/Consumer/Consumer.dll
            
        depends_on:
            - redis
            
    producer:
        build:
            context: .
            dockerfile: ubuntu.14.04-x64/Producer/linux-producer.docker
            
        environment:
            Tachyon_RedisConnectionMultiplexer: 192.168.51.11 
        
        entrypoint:
            - dotnet
            - ubuntu.14.04-x64/Producer/Producer.dll
            
        depends_on:
            - redis